[GeneralSettings]
LogAppStartupProgress = False
UseTableEntryHeaders = True
AllowSingleTableMode = True
InsertAutoActive = True
ShowMatrixGrid = True
FocusOnGotoShortcuts = True
ZoomLevel = 18
MaximumDiffSegments = 1000
MaximumSearchResults = 1000
CopyLimit = 40000
AnimateScroll = True
AutoAdjustDataWidth = True
StretchData = True
AllowMultipleElementsPerLine = False
IsNewVersionAvailable = False
LastUpdateCheck = 2026-03-08 1:31:14 PM
AcknowledgeTutorials = False
Base10Length = False
SpartanMode = False
MapTutorials = '''001000000000000001000001000000000000'''
RecentFiles = ["D:\Workfiles\01_Personnal\08_Pokemon_RomHack\Build\Pokemon - Emerald Version  - TestRomHack.gba"]

[Theme]
PrimaryColor = "#dddddd"
BackgroundColor = "#222222"
HueOffset= 0.1
AccentSaturation = 0.7
AccentValue = 0.7
HighlightBrightness = 0.6
